### ISSUE TITLE
who is the target audience for this tool?

### ISSUE THREAD

**Issue by ghost** [recursecenter/hs-cli#10]
Hi! the name of the project attracted me here. Who is the target audience for this tool? is it meant for internal use in Hacker School? or a way for me to obtain data you have made open about Hacker School?

**Comment by ghost** [comment]
I got a clearer idea by reading the parts "Request code review" and "Review code", I haven't tried the gem out myself but this is my understanding: It is a tool to ask for help with a problem and when someone wants to help, they use this tool again to do a bunch of routing actions like cloning/branching/pulling to be automatically brought to the part where the person indicated he/she wants help. 

Have I understood correctly?

**Comment by zachallaun** [comment]
Hi there!

Yes, that was one of the primary use cases. This is a deprecated experiment that has since been replaced with other internal tools at Hacker School. There are no plans to continue to add features or maintain this project – if you find the existing code useful, please feel free to fork the project :).

Thanks, Sindhu!
